-- 회원 테이블 생성
CREATE TABLE USERS(
    USER_ID NUMBER(10) PRIMARY KEY,
    USER_NAME VARCHAR2(10),
    PW VARCHAR(20),
    BIRTH VARCHAR2(8),
    EMAIL VARCHAR2(30),
    ADDRESS VARCHAR2(30),
    SEX_CODE NUMBER(1),
    ACCOUNT_NUM VARCHAR2(12)
);

-- 계좌 테이블 생성
CREATE TABLE ACCOUNT(
    ACCOUNT_ID NUMBER(10) PRIMARY KEY,
    OPEN_DATE DATE,
    OPEN_POINT VARCHAR2(20),
    ACCOUNT_OWNER VARCHAR2(10),
    BALANCE NUMBER(15),
    IS_OPEN_BANK VARCHAR2(1),
    ACCOUNT_NUM VARCHAR2(12),
    USER_ID NUMBER(10),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 은행 테이블 생성
CREATE TABLE BANK(
    BANK_ID NUMBER(10) PRIMARY KEY,
    BANK_NAME VARCHAR2(20),
    BANK_TEL VARCHAR2(20),
    BANK_LOCATION VARCHAR2(20),
    ACCOUNT_ID NUMBER(10),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);
    
SELECT * FROM USERS;
SELECT * FROM ACCOUNT;
SELECT * FROM BANK;

-- 테이블 삭제
DROP TABLE USERS;
DROP TABLE ACCOUNT;
DROP TABLE BANK;